version: 2.1
jobs:
  build:
    docker:
      - image: ruby:3.1.1
    steps:
      - checkout
      - run: gem install bundler -v 2.3.7
      - run: bundle install
      - run: bundle exec appraisal
      - run: bundle exec appraisal rake test
      - store_test_results:
          path: test/reports
      - store_artifacts:
          path: coverage
  rubocop:
    docker:
      - image: ruby:3.1.1
    steps:
      - checkout
      - run: gem install bundler -v 2.3.7
      - run: bundle install
      - run: bundle exec rubocop

workflows:
  build:
    jobs:
      - build
      - rubocop