version: 2.1

orbs:
  ruby: circleci/ruby@2.0.0

jobs:
  build:
    docker:
      - image: ruby:3.1.1
    steps:
      - checkout
      - ruby/install-deps
      - run: bundle exec appraisal
      - run: bundle exec appraisal rake test
      - store_test_results:
          path: test/reports
      - store_artifacts:
          path: coverage
  rubocop:
    docker:
      - image: ruby:3.1.1
    steps:
      - checkout
      - ruby/install-deps
      - run: bundle exec rubocop

workflows:
  build:
    jobs:
      - build
      - rubocop